### ISSUE TITLE
Unable to get it running when installing on Ubuntu using Snap

### ISSUE THREAD

**Issue by JohnMcLear** [JanLochi/zigbee2mqtt-snap#6]
```
jose@ryzin:/snap/janlochi-zigbee2mqtt/34/bin$ snap logs janlochi-zigbee2mqtt
2021-11-17T17:41:42Z janlochi-zigbee2mqtt.zigbee2mqtt[386434]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-11-17T17:41:42Z janlochi-zigbee2mqtt.zigbee2mqtt[386434]: npm ERR! A complete log of this run can be found in:
2021-11-17T17:41:42Z janlochi-zigbee2mqtt.zigbee2mqtt[386434]: npm ERR!     /root/snap/janlochi-zigbee2mqtt/34/.npm/_logs/2021-11-17T17_41_42_308Z-debug.log
2021-11-17T17:41:42Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Main process exited, code=exited, status=1/FAILURE
2021-11-17T17:41:42Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Failed with result 'exit-code'.
2021-11-17T17:41:42Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Scheduled restart job, restart counter is at 5.
2021-11-17T17:41:42Z systemd[1]: Stopped Service for snap application janlochi-zigbee2mqtt.zigbee2mqtt.
2021-11-17T17:41:42Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Start request repeated too quickly.
2021-11-17T17:41:42Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Failed with result 'exit-code'.
2021-11-17T17:41:42Z systemd[1]: Failed to start Service for snap application janlochi-zigbee2mqtt.zigbee2mqtt.
jose@ryzin:/snap/janlochi-zigbee2mqtt/34/bin$ sudo cat /root/snap/janlochi-zigbee2mqtt/34/.npm/_logs/2021-11-17T17_41_42_308Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/snap/janlochi-zigbee2mqtt/34/bin/node',
1 verbose cli   '/snap/janlochi-zigbee2mqtt/34/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--prefix',
1 verbose cli   '/snap/janlochi-zigbee2mqtt/34/lib/node_modules/zigbee2mqtt'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zigbee2mqtt@1.19.1~prestart: zigbee2mqtt@1.19.1
6 info lifecycle zigbee2mqtt@1.19.1~start: zigbee2mqtt@1.19.1
7 verbose lifecycle zigbee2mqtt@1.19.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle zigbee2mqtt@1.19.1~start: PATH: /snap/janlochi-zigbee2mqtt/34/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/snap/janlochi-zigbee2mqtt/34/lib/node_modules/zigbee2mqtt/node_modules/.bin:/snap/janlochi-zigbee2mqtt/34/lib/node_modules/.bin:/snap/janlochi-zigbee2mqtt/34/usr/sbin:/snap/janlochi-zigbee2mqtt/34/usr/bin:/snap/janlochi-zigbee2mqtt/34/sbin:/snap/janlochi-zigbee2mqtt/34/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle zigbee2mqtt@1.19.1~start: CWD: /snap/janlochi-zigbee2mqtt/34/lib/node_modules/zigbee2mqtt
10 silly lifecycle zigbee2mqtt@1.19.1~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle zigbee2mqtt@1.19.1~start: Returned: code: 1  signal: null
12 info lifecycle zigbee2mqtt@1.19.1~start: Failed to exec start script
13 verbose stack Error: zigbee2mqtt@1.19.1 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/snap/janlochi-zigbee2mqtt/34/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:376:20)
13 verbose stack     at ChildProcess.<anonymous> (/snap/janlochi-zigbee2mqtt/34/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:376:20)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid zigbee2mqtt@1.19.1
15 verbose cwd /var/snap/janlochi-zigbee2mqtt/34
16 verbose Linux 5.11.0-40-generic
17 verbose argv "/snap/janlochi-zigbee2mqtt/34/bin/node" "/snap/janlochi-zigbee2mqtt/34/bin/npm" "start" "--prefix" "/snap/janlochi-zigbee2mqtt/34/lib/node_modules/zigbee2mqtt"
18 verbose node v14.17.0
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error zigbee2mqtt@1.19.1 start: `node index.js`
22 error Exit status 1
23 error Failed at the zigbee2mqtt@1.19.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I'm pretty sure it's user error..  Will continue digging

**Comment by JanLochi** [comment]
Maybe you have more success when using the version from the edge channel?

`
snap refresh janlochi-zigbee2mqtt --edge
`

**Comment by JohnMcLear** [comment]
No dice on that.

```
2021-11-19T09:26:41Z janlochi-zigbee2mqtt.zigbee2mqtt[428728]: Zigbee2MQTT:info  2021-11-19 09:26:41: Stopped Zigbee2MQTT
2021-11-19T09:26:41Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Succeeded.
2021-11-19T09:26:41Z systemd[1]: Stopped Service for snap application janlochi-zigbee2mqtt.zigbee2mqtt.
2021-11-19T09:26:43Z systemd[1]: Started Service for snap application janlochi-zigbee2mqtt.zigbee2mqtt.
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455181]: > zigbee2mqtt@1.21.2 start /snap/janlochi-zigbee2mqtt/39/lib/node_modules/zigbee2mqtt
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455181]: > node index.js
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]: Building Zigbee2MQTT... (initial build), failed
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]: (node:455246) UnhandledPromiseRejectionWarning: Error: Command failed: npm run build
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]: npm ERR! code ELIFECYCLE
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]: npm ERR! errno 2
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]: npm ERR! zigbee2mqtt@1.21.2 build: `tsc && node index.js writehash`
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]: npm ERR! Exit status 2
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]: npm ERR!
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]: npm ERR! Failed at the zigbee2mqtt@1.21.2 build script.
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]: npm ERR! A complete log of this run can be found in:
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]: npm ERR!     /root/snap/janlochi-zigbee2mqtt/39/.npm/_logs/2021-11-19T09_26_45_643Z-debug.log
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]:     at ChildProcess.exithandler (child_process.js:383:12)
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]:     at ChildProcess.emit (events.js:400:28)
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]:     at maybeClose (internal/child_process.js:1058:16)
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]: (node:455246) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-11-19T09:26:45Z janlochi-zigbee2mqtt.zigbee2mqtt[455246]: (node:455246) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-11-19T09:26:45Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Succeeded.
2021-11-19T09:27:05Z systemd[1]: Started Service for snap application janlochi-zigbee2mqtt.zigbee2mqtt.
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455390]: > zigbee2mqtt@1.21.2 start /snap/janlochi-zigbee2mqtt/39/lib/node_modules/zigbee2mqtt
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455390]: > node index.js
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]: Building Zigbee2MQTT... (initial build), failed
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]: (node:455433) UnhandledPromiseRejectionWarning: Error: Command failed: npm run build
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]: npm ERR! code ELIFECYCLE
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]: npm ERR! errno 2
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]: npm ERR! zigbee2mqtt@1.21.2 build: `tsc && node index.js writehash`
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]: npm ERR! Exit status 2
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]: npm ERR!
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]: npm ERR! Failed at the zigbee2mqtt@1.21.2 build script.
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]: npm ERR! A complete log of this run can be found in:
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]: npm ERR!     /root/snap/janlochi-zigbee2mqtt/39/.npm/_logs/2021-11-19T09_27_06_470Z-debug.log
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]:     at ChildProcess.exithandler (child_process.js:383:12)
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]:     at ChildProcess.emit (events.js:400:28)
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]:     at maybeClose (internal/child_process.js:1058:16)
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]: (node:455433) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-11-19T09:27:06Z janlochi-zigbee2mqtt.zigbee2mqtt[455433]: (node:455433) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-11-19T09:27:06Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Succeeded.
```

Log file output

```
 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/snap/janlochi-zigbee2mqtt/39/bin/node',
1 verbose cli   '/snap/janlochi-zigbee2mqtt/39/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.18.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle zigbee2mqtt@1.21.2~prebuild: zigbee2mqtt@1.21.2
6 info lifecycle zigbee2mqtt@1.21.2~build: zigbee2mqtt@1.21.2
7 verbose lifecycle zigbee2mqtt@1.21.2~build: unsafe-perm in lifecycle true
8 verbose lifecycle zigbee2mqtt@1.21.2~build: PATH: /snap/janlochi-zigbee2mqtt/39/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/snap/janlochi-zigbee2mqtt/39/lib/node_modules/zigbee2mqtt/node_modules/.bin:/snap/janlochi-zigbee2mqtt/39/lib/node_modules/.bin:/snap/janlochi-zigbee2mqtt/39/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/snap/janlochi-zigbee2mqtt/39/lib/node_modules/zigbee2mqtt/node_modules/.bin:/snap/janlochi-zigbee2mqtt/39/lib/node_modules/.bin:/snap/janlochi-zigbee2mqtt/39/usr/sbin:/snap/janlochi-zigbee2mqtt/39/usr/bin:/snap/janlochi-zigbee2mqtt/39/sbin:/snap/janlochi-zigbee2mqtt/39/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle zigbee2mqtt@1.21.2~build: CWD: /snap/janlochi-zigbee2mqtt/39/lib/node_modules/zigbee2mqtt
10 silly lifecycle zigbee2mqtt@1.21.2~build: Args: [ '-c', 'tsc && node index.js writehash' ]
11 silly lifecycle zigbee2mqtt@1.21.2~build: Returned: code: 2  signal: null
12 info lifecycle zigbee2mqtt@1.21.2~build: Failed to exec build script
13 verbose stack Error: zigbee2mqtt@1.21.2 build: `tsc && node index.js writehash`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/snap/janlochi-zigbee2mqtt/39/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/snap/janlochi-zigbee2mqtt/39/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid zigbee2mqtt@1.21.2
15 verbose cwd /snap/janlochi-zigbee2mqtt/39/lib/node_modules/zigbee2mqtt
16 verbose Linux 5.11.0-40-generic
17 verbose argv "/snap/janlochi-zigbee2mqtt/39/bin/node" "/snap/janlochi-zigbee2mqtt/39/bin/npm" "run" "build"
18 verbose node v14.18.1
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 2
22 error zigbee2mqtt@1.21.2 build: `tsc && node index.js writehash`
22 error Exit status 2
23 error Failed at the zigbee2mqtt@1.21.2 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by JohnMcLear** [comment]
I went back to stable and I have it working.  Let's leave this issue open so we can fix up edge?  HTH once you push a fix, fwiw I installed ``tsc`` and have it available on CLI but the same error persists.

**Comment by JanLochi** [comment]
Agreed, I will have a look into it.

**Comment by JanLochi** [comment]
Hi @JohnMcLear 

It took soooooome time 😁, but edge has a new version. If you want to give it a try?

Thx,
Jan

**Comment by JohnMcLear** [comment]
```
jose@ryzin:~$ snap logs janlochi-zigbee2mqtt
2023-02-08T11:05:19Z janlochi-zigbee2mqtt.zigbee2mqtt[4235]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2023-02-08T11:05:19Z janlochi-zigbee2mqtt.zigbee2mqtt[4235]: npm ERR! A complete log of this run can be found in:
2023-02-08T11:05:19Z janlochi-zigbee2mqtt.zigbee2mqtt[4235]: npm ERR!     /root/snap/janlochi-zigbee2mqtt/34/.npm/_logs/2023-02-08T11_05_19_011Z-debug.log
2023-02-08T11:05:19Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Main process exited, code=exited, status=1/FAILURE
2023-02-08T11:05:19Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Failed with result 'exit-code'.
2023-02-08T11:05:19Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Scheduled restart job, restart counter is at 10.
2023-02-08T11:05:19Z systemd[1]: Stopped Service for snap application janlochi-zigbee2mqtt.zigbee2mqtt.
2023-02-08T11:05:19Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Start request repeated too quickly.
2023-02-08T11:05:19Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Failed with result 'exit-code'.
2023-02-08T11:05:19Z systemd[1]: Failed to start Service for snap application janlochi-zigbee2mqtt.zigbee2mqtt.
jose@ryzin:~$ snap refresh janlochi-zigbee2mqtt --edge
janlochi-zigbee2mqtt (edge) 1.30.1-14 from Jan Lochmatter (o-jan-l) refreshed
jose@ryzin:~$ sudo snap restart janlochi-zigbee2mqtt
Restarted.
jose@ryzin:~$ snap logs janlochi-zigbee2mqtt
2023-03-02T10:00:44Z janlochi-zigbee2mqtt.zigbee2mqtt[252991]:     at /snap/janlochi-zigbee2mqtt/46/app/node_modules/@serialport/stream/dist/index.js:112:18
2023-03-02T10:00:44Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Main process exited, code=exited, status=1/FAILURE
2023-03-02T10:00:44Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Failed with result 'exit-code'.
2023-03-02T10:00:44Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Consumed 1.607s CPU time.
2023-03-02T10:00:44Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Scheduled restart job, restart counter is at 5.
2023-03-02T10:00:44Z systemd[1]: Stopped Service for snap application janlochi-zigbee2mqtt.zigbee2mqtt.
2023-03-02T10:00:44Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Consumed 1.607s CPU time.
2023-03-02T10:00:44Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Start request repeated too quickly.
2023-03-02T10:00:44Z systemd[1]: snap.janlochi-zigbee2mqtt.zigbee2mqtt.service: Failed with result 'exit-code'.
2023-03-02T10:00:44Z systemd[1]: Failed to start Service for snap application janlochi-zigbee2mqtt.zigbee2mqtt.
```

Doesn't look like it's working.  Sorry!

**Comment by JanLochi** [comment]
Hey. Thx for testing. Very much appreciated.

The app crashes while trying to access the serial port. Is you port config correct and the snap slot connected?

Regards

**Comment by JohnMcLear** [comment]
Good shout, I haven't tried in a while and don't have a router in this box any more to test with.  Apologies but this can probably be closed as working!

**Comment by JanLochi** [comment]
Thx for letting me know 👌
